### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mammadkoma** [Nerixyz/InstagramLiveGUI#1]
Hello , I installed OBS Studio 26.1.1 and obs-websocket-4.9.0-Windows-Installer.exe and open obs studio.
I start the wpf project and enter my insta user and pass live account and click on login button then Start Stream button , the project stop in StartStreamViewModel.cs file on line 59 : 
OBSWebsocketDotNet.AuthFailureException: 'Exception of type 'OBSWebsocketDotNet.AuthFailureException' was thrown.'
This exception was originally thrown at this call stack:
    [External Code]
    InstaStream.Models.InstagramSession.StartStream() in InstagramSession.cs
    [External Code]
    InstaStream.ViewModels.StartStreamViewModel.StartStream() in StartStreamViewModel.cs
![image](https://user-images.githubusercontent.com/17564001/116525483-cfaeff80-a8ed-11eb-84a7-67c592cdbeae.png)
stack trace : 
   at OBSWebsocketDotNet.OBSWebsocket.Authenticate(String password, OBSAuthInfo authInfo)
   at OBSWebsocketDotNet.OBSWebsocket.Connect(String url, String password)
   at InstaStream.Models.InstagramSession.<StartStream>d__71.MoveNext() in C:\Users\mammadkoma\Desktop\InstagramLiveGUI-master\InstaStream\Models\InstagramSession.cs:line 162
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at InstaStream.ViewModels.StartStreamViewModel.<StartStream>d__14.MoveNext() in C:\Users\mammadkoma\Desktop\InstagramLiveGUI-master\InstaStream\ViewModels\StartStreamViewModel.cs:line 59

**Comment by Nerixyz** [comment]
You probably set up a user/password for obs-websocket. This app requires the credentials to be empty.

**Comment by mammadkoma** [comment]
When I login without user/pass in wpf that error occur.

**Comment by Nerixyz** [comment]
On which port is the websocket and is the websocket started?

**Comment by mammadkoma** [comment]
4444

**Comment by Nerixyz** [comment]
You have authentication turned on. Turn it off.

**Comment by mammadkoma** [comment]
Could you send a video to use this wpf app please?

**Comment by Nerixyz** [comment]
No.
But this is how the settings should be:

![OBS Websocket settings](https://i.imgur.com/K53JFjK.png)

Else you just click your way through.

**Comment by mammadkoma** [comment]
Thank you that error gone.
Now after share my laptop camera in obs , show this message:
![image](https://user-images.githubusercontent.com/17564001/116537992-3509ed00-a8fc-11eb-8cfa-024e0bf17be4.png)

**Comment by Nerixyz** [comment]
Your stream output should be on `Custom...`.

**Comment by mammadkoma** [comment]
yes it is
![image](https://user-images.githubusercontent.com/17564001/116538537-e872e180-a8fc-11eb-8ef1-dd9cc4d1a090.png)

**Comment by Nerixyz** [comment]
Then it should work.

**Comment by mammadkoma** [comment]
this message appear :
![image](https://user-images.githubusercontent.com/17564001/116538974-7a7aea00-a8fd-11eb-980a-268c332433c2.png)
And in my phone shows dark screen in live.

**Comment by mammadkoma** [comment]
![Screenshot_20210429-151425](https://user-images.githubusercontent.com/17564001/116539290-de051780-a8fd-11eb-9583-63d99e5cf090.png)

**Comment by Nerixyz** [comment]
That's weird. I suspect it's something with the url.
